export type Vehicle={id:number;brand:string;model:string;year:number;plate:string;mileage:number;price:number;cost:number;prep:number;paid:number;buyer:string;status:string;published:number;photo:string;description:string;inspection:string;createdAt:string;updatedAt:string};
export type Line={name:string;kind:string;qty:number;rate:number};
export type Job={id:number;customer:string;phone:string;bike:string;plate:string;mileage:number;complaint:string;notes:string;mechanic:string;status:string;items:string;paid:number;createdAt:string;updatedAt:string};
export const bikeStatuses:Record<string,string>={available:'Available',reserved:'Reserved',sold:'Sold'};
export const jobStatuses:Record<string,string>={new:'Baharu',working:'Dalam kerja',ready:'Siap',collected:'Diserahkan'};
export const inspectionLabels=['Enjin & kebocoran','Brek hadapan / belakang','Tayar & rim','Lampu & signal','Rantai / belt','Bateri & starter','Suspensi','Dokumen & nombor casis'];
export const money=(n:number)=>new Intl.NumberFormat('ms-MY',{style:'currency',currency:'MYR',maximumFractionDigits:2}).format(n/100);
export function parseLines(s:string):Line[]{try{return JSON.parse(s)}catch{return []}}
export const total=(j:Pick<Job,'items'>)=>parseLines(j.items).reduce((s,l)=>s+l.qty*l.rate,0);
export const vehicleId=(id:number)=>'3AM-'+String(id).padStart(4,'0');
export const jobId=(id:number)=>'JOB-'+String(id).padStart(4,'0');
export const demoVehicles:Vehicle[]=[['Yamaha','Y15ZR',2023,780000,'available'],['Honda','RS-X',2022,650000,'reserved'],['Yamaha','NVX 155',2024,1050000,'available'],['Honda','Wave Alpha',2021,350000,'available'],['Yamaha','LC135',2022,590000,'sold'],['SYM','VF3i 185',2023,680000,'available']].map((r,i)=>({id:9001+i,brand:String(r[0]),model:String(r[1]),year:Number(r[2]),price:Number(r[3]),status:String(r[4]),plate:'',mileage:12000+i*2300,cost:0,prep:0,paid:0,buyer:'',published:1,photo:'',description:'Contoh paparan. Maklumat dan harga ini bukan stok sebenar 3 Abdul Motor.',inspection:'[]',createdAt:'',updatedAt:''}));
export const demoJobs:Job[]=[{id:9001,customer:'Pelanggan contoh A',phone:'',bike:'Yamaha Y15ZR',plate:'CONTOH 01',mileage:18000,complaint:'Servis berkala · minyak enjin & pemeriksaan brek',notes:'',mechanic:'Mekanik A',status:'working',items:JSON.stringify([{name:'Minyak enjin',kind:'part',qty:1,rate:4500},{name:'Upah servis',kind:'labour',qty:1,rate:1500}]),paid:0,createdAt:'',updatedAt:''},{id:9002,customer:'Pelanggan contoh B',phone:'',bike:'Honda RS-X',plate:'CONTOH 02',mileage:12000,complaint:'Tukar pad brek hadapan',notes:'',mechanic:'Mekanik B',status:'ready',items:JSON.stringify([{name:'Pad brek',kind:'part',qty:1,rate:5500},{name:'Upah',kind:'labour',qty:1,rate:2000}]),paid:7500,createdAt:'',updatedAt:''},{id:9003,customer:'Pelanggan contoh C',phone:'',bike:'Yamaha NVX',plate:'CONTOH 03',mileage:9000,complaint:'Pemeriksaan bunyi pada bahagian CVT',notes:'',mechanic:'',status:'new',items:'[]',paid:0,createdAt:'',updatedAt:''}];
