import type {Vehicle,Job,Payment} from './motor';
import {money,dateText,total,parseLines,vehicleId,jobId,jobStatuses,paymentStatus} from './motor';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function printRecord(record:Vehicle|Job,payments:Payment[],documentType:'invoice'|'estimate'|'receipt'='invoice'){
 const vehicle='brand'in record;const id=vehicle?vehicleId(record.id):jobId(record.id);const amount=vehicle?record.price:total(record);const title=documentType==='estimate'?'Anggaran servis':documentType==='receipt'?'Resit bayaran':vehicle?'Invois jualan':'Invois servis';
 const rows=vehicle?'<tr><td>'+escape(record.brand+' '+record.model)+'<br/><small>Tahun '+record.year+' · '+escape(record.plate)+' · Casis '+escape(record.chassis||'—')+'</small></td><td>1</td><td>'+money(record.price)+'</td><td>'+money(record.price)+'</td></tr>':parseLines(record.items).map(l=>'<tr><td>'+escape(l.name)+'<br/><small>'+escape(l.kind==='part'?'Alat ganti':'Upah')+'</small></td><td>'+l.qty+'</td><td>'+money(l.rate)+'</td><td>'+money(l.qty*l.rate)+'</td></tr>').join('');
 const ledger=documentType==='estimate'?'':`<h3>Transaksi bayaran</h3><table><tr><th>Rujukan / tarikh</th><th>Kaedah / penerima</th><th>Jumlah</th></tr>${payments.map(p=>'<tr><td>PAY-'+p.id+'<br/>'+escape(dateText(p.paidAt))+'<br/><small>'+escape(p.note)+'</small></td><td>'+escape(({cash:'Tunai',transfer:'Transfer',card:'Kad'} as Record<string,string>)[p.method]||p.method)+'<br/>'+escape(p.receiverName)+'</td><td>'+money(p.amount)+'</td></tr>').join('')}</table>`;
 const w=window.open('','_blank');if(!w)throw Error('Benarkan pop-up untuk cetak atau simpan PDF.');
 w.addEventListener('load',()=>{w.focus();w.print()},{once:true});
 w.document.write(`<!doctype html><html lang="ms"><head><meta charset="utf-8"><title>${escape(title+' '+id)}</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111;line-height:1.5;max-width:850px;margin:auto}header{display:flex;align-items:center;justify-content:space-between;border-bottom:4px solid #eac000;padding-bottom:16px}img{width:90px}h1{font-size:23px}h2{font-size:20px}table{border-collapse:collapse;width:100%;margin:20px 0}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}small{color:#555}.totals{text-align:right}.note{white-space:pre-wrap}footer{margin-top:28px;font-size:11px;color:#777}@media print{body{padding:0}tr{break-inside:avoid}}</style></head><body><header><div><h1>3 ABDUL MOTOR</h1><span>${escape(title)} · ${id}</span></div><img src="${escape(location.origin+location.pathname+'icon-192.png')}" alt="3 Abdul Motor"></header><p>Dicetak: ${escape(dateText(new Date().toISOString()))}</p><p><b>${escape(vehicle?record.buyer||'Pembeli belum direkodkan':record.customer)}</b><br/>${escape(vehicle?record.buyerPhone||'':record.phone)}</p>${!vehicle?'<p><b>'+escape(record.bike+' / '+record.plate)+'</b><br/>Status kerja: '+escape(jobStatuses[record.status])+' · Mekanik: '+escape(record.mechanic||'—')+'</p><p class="note">'+escape(record.complaint)+'</p>':''}<table><tr><th>Butiran</th><th>Kuantiti</th><th>Harga</th><th>Jumlah</th></tr>${rows}</table><div class="totals"><p>Jumlah: <b>${money(amount)}</b></p>${documentType!=='estimate'?'<p>Dibayar: '+money(record.paid)+'</p><p>Baki: <b>'+money(Math.max(0,amount-record.paid))+'</b></p><p>'+escape(paymentStatus(record.paid,amount))+'</p>':''}</div>${!vehicle&&documentType==='estimate'?'<p class="note">Persetujuan pelanggan: '+escape(record.approvalNote||'Belum direkodkan')+'</p>':''}${!vehicle&&record.status==='collected'&&record.paid<amount?'<p class="note">Serahan dengan baki diluluskan owner: '+escape(record.creditReason)+'</p>':''}${ledger}<footer>3 Abdul Motor · Built by BinaLab</footer></body></html>`);w.document.close();
}
