import {supabase,getStaff} from './supabase';
import {vehicle,job} from './validation';
import type {Vehicle,Job} from './motor';
export function mapRow(row:Record<string,unknown>):Vehicle|Job{const data:Record<string,unknown>={};for(const [k,v]of Object.entries(row)){data[k.replace(/_([a-z])/g,(_,l:string)=>l.toUpperCase())]=['items','inspection'].includes(k)?JSON.stringify(v):v;}return data as Vehicle|Job;}
export async function loadRecords(kind:string):Promise<(Vehicle|Job)[]>{if(!supabase){if(kind==='catalogue')return [];throw new Error('Sistem sedang disediakan. Sila hubungi pentadbir.');}const table=kind==='catalogue'?'catalogue':kind;if(!['catalogue','vehicles','jobs'].includes(table))throw Error('Rekod tidak sah.');const {data,error}=await supabase.from(table).select('*').order('id',{ascending:false});if(error)throw Error('Rekod gagal dimuatkan. Cuba semula.');return Promise.all((data??[]).map(async(row)=>{const mapped=mapRow(row);if('photo'in mapped&&mapped.photo){const {data:photo}=await supabase!.storage.from('vehicle-photos').createSignedUrl(mapped.photo,3600);mapped.photo=photo?.signedUrl??'';}return mapped;}));}
export async function saveRecord(kind:'vehicles'|'jobs',value:Vehicle|Job,update:boolean){if(!supabase)throw Error('Sistem belum tersedia.');if(!await getStaff())throw Error('Akses admin tidak dibenarkan.');let candidate={...value};if('photo'in candidate&&candidate.photo.startsWith('https://')){const path=candidate.photo.split('/vehicle-photos/')[1]?.split('?')[0];if(!path)throw Error('Foto tidak sah.');candidate={...candidate,photo:decodeURIComponent(path)};}
const parsed=(kind==='vehicles'?vehicle:job).safeParse(candidate);if(!parsed.success)throw Error(parsed.error.issues[0]?.message||'Semak maklumat.');const payload:Record<string,unknown>={};for(const [k,v]of Object.entries(parsed.data)){payload[k.replace(/[A-Z]/g,m=>'_'+m.toLowerCase())]=['items','inspection'].includes(k)?JSON.parse(v as string):k==='published'?!!v:v;}
const query=update?supabase.from(kind).update(payload).eq('id',value.id):supabase.from(kind).insert(payload);const {data,error}=await query.select('id').single();if(error)throw Error('Rekod gagal disimpan. Semak akses dan maklumat, kemudian cuba semula.');return data;}
export async function uploadPhoto(file:File){if(!supabase)throw Error('Sistem belum tersedia.');if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>5*1024*1024)throw Error('Gunakan JPG, PNG atau WebP di bawah 5 MB.');const key=crypto.randomUUID()+'.'+({'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type]);const {error}=await supabase.storage.from('vehicle-photos').upload(key,file,{upsert:false,cacheControl:'3600'});if(error)throw Error('Foto gagal dimuat naik. Cuba semula.');const {data,error:signedError}=await supabase.storage.from('vehicle-photos').createSignedUrl(key,3600);if(signedError||!data)throw Error('Foto belum dapat dipaparkan. Cuba semula.');return data.signedUrl;}
