import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import ts from 'typescript';
const source=ts.transpileModule(readFileSync(new URL('../supabase/functions/manage-staff/index.ts',import.meta.url),'utf8').replace(/^import[^\n]+\n/,''),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ES2022}}).outputText;
function setup({actor={id:'owner',role:'owner',enabled:true,must_change_password:false},valid=true,target={id:'target',role:'inventory'},rpcError=null}={}){const calls=[];let handler;let reads=0;const admin={auth:{getUser:async(token)=>{calls.push(['verify',token]);return {data:{user:valid?{id:actor.id}:null},error:valid?null:Error('invalid')}},admin:{createUser:async(values)=>{calls.push(['create',values]);return {data:{user:{id:'new-staff'}},error:null}},deleteUser:async(id)=>{calls.push(['rollback',id]);return {error:null}}}},from:()=>{const q={select:()=>q,eq:()=>q,maybeSingle:async()=>({data:reads++?target:actor,error:null}),update:()=>q};return q},rpc:async(name,args)=>{calls.push(['rpc',name,args]);return {error:rpcError}}};new Function('createClient','Deno',source)(()=>admin,{env:{get:(key)=>key==='SUPABASE_URL'?'https://project.supabase.co':'test-server-only-key'},serve:fn=>{handler=fn}});return {handler,calls}}
const request=(data,token='valid-token')=>new Request('https://project.supabase.co/functions/v1/manage-staff',{method:'POST',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(data)});
const staff={display_name:'Test staff',role:'inventory',enabled:true,permissions:{inventory_edit:true,garage_edit:false,receive_payments:false,publish_catalogue:false,manage_whatsapp:false,manage_photos:true},payment_limit:50000};
test('unauthenticated and invalid JWT requests cannot manage staff',async()=>{const a=setup();assert.equal((await a.handler(request({action:'list'},''))).status,401);assert.equal(a.calls.length,0);const b=setup({valid:false});assert.equal((await b.handler(request({action:'create'}))).status,401);assert.equal(b.calls.some(c=>c[0]==='create'),false)});
test('ordinary, disabled and temporary users cannot manage access',async()=>{for(const actor of [{id:'staff',role:'both',enabled:true},{id:'owner',role:'owner',enabled:false},{id:'owner',role:'owner',enabled:true,must_change_password:true}]){const s=setup({actor});assert.equal((await s.handler(request({action:'create'}))).status,403);assert.equal(s.calls.some(c=>c[0]==='create'),false)}});
test('owner account and owner role escalation are protected',async()=>{const s=setup({target:{id:'other-owner',role:'owner'}});assert.equal((await s.handler(request({action:'update',id:'other-owner',version:1,staff}))).status,403);const b=setup();assert.equal((await b.handler(request({action:'create',email:'test@example.com',password:'Temporary_Safe_2026',staff:{...staff,role:'owner'}}))).status,400);assert.equal(b.calls.some(c=>c[0]==='create'),false)});
test('new staff Auth provisioning and atomic profile write use verified actor',async()=>{const s=setup();assert.equal((await s.handler(request({action:'create',email:'TEST@example.com',password:'Temporary_Safe_2026',staff}))).status,200);const auth=s.calls.find(c=>c[0]==='create');assert.equal(auth[1].email,'test@example.com');assert.equal(auth[1].email_confirm,true);const rpc=s.calls.find(c=>c[0]==='rpc');assert.equal(rpc[2].actor_id,'owner');assert.equal(rpc[2].target_id,'new-staff');assert.equal(rpc[2].expected_version,null);assert.equal('password' in rpc[2].details,false)});
test('failed profile write rolls back only the newly provisioned account',async()=>{const s=setup({rpcError:Error('database offline')});assert.equal((await s.handler(request({action:'create',email:'test@example.com',password:'Temporary_Safe_2026',staff}))).status,500);assert.deepEqual(s.calls.find(c=>c[0]==='rollback'),['rollback','new-staff'])});
