'use client';
import {useState,useEffect,useCallback} from 'react';
import {loadRecords,saveRecord,uploadPhoto} from '@/lib/records';
import {Bike, Wrench, Package, Search, Plus, ShieldCheck, Gauge, CalendarDays, ClipboardList, CircleCheck, Wallet, Printer, ImagePlus, X, RefreshCw, Eye, Banknote, Layers, ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {Vehicle,Job,Line,demoVehicles,demoJobs,money,total,parseLines,vehicleId,jobId,bikeStatuses,jobStatuses,inspectionLabels} from '@/lib/motor';

type Mode='catalogue'|'inventory'|'garage';
const blankBike:Vehicle={id:0,brand:'',model:'',year:new Date().getFullYear(),plate:'',mileage:0,price:0,cost:0,prep:0,paid:0,buyer:'',status:'available',published:1,photo:'',description:'',inspection:'[]',createdAt:'',updatedAt:''};
const blankJob:Job={id:0,customer:'',phone:'',bike:'',plate:'',mileage:0,complaint:'',notes:'',mechanic:'',status:'new',items:'[]',paid:0,createdAt:'',updatedAt:''};
function Picker({value,onChange,options}:{value:string;onChange:(s:string)=>void;options:Record<string,string>}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(options).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Badge({status,garage=false}:{status:string;garage?:boolean}){return <span className={'status '+status}>{(garage?jobStatuses:bikeStatuses)[status]}</span>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="field"><span>{label}</span>{children}</label>}
function NumberField({label,value,onChange,cents=false}:{label:string;value:number;onChange:(n:number)=>void;cents?:boolean}){return <Field label={label}><input type="number" min="0" step={cents?'0.01':'1'} value={cents?value/100:value} onChange={e=>onChange(cents?Math.round(Number(e.target.value)*100):Number(e.target.value))}/></Field>}
function Logo(){return <a className="brand" href="#catalogue" aria-label="3 Abdul Motor — katalog"><img src="./logo-transparent-v2.png" alt="3 Abdul Motor"/><span className="brand-caption">Jual beli · Servis</span></a>}
function BikePhoto({v}:{v:Vehicle}){return <div className={'bike-photo '+(!v.photo?'no-photo':'')}>{v.photo?<img src={v.photo} alt={v.brand+' '+v.model} loading="lazy" decoding="async"/>:<><Bike size={76} strokeWidth={1.1}/><span>Foto belum dimuat naik</span></>}<Badge status={v.status}/></div>}
const nav=[{mode:'catalogue',href:'#catalogue',label:'Katalog',icon:Bike},{mode:'inventory',href:'#inventory',label:'Inventori',icon:Package},{mode:'garage',href:'#garage',label:'Garage',icon:Wrench}];
export default function MotorApp({mode}:{mode:Mode}){
 const admin=mode!=='catalogue';const [records,setRecords]=useState<(Vehicle|Job)[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [brand,setBrand]=useState('all');const [selected,setSelected]=useState<Vehicle|Job|null>(null);const [adding,setAdding]=useState(false);const [detail,setDetail]=useState<Vehicle|Job|null>(null);
 const kind=mode==='garage'?'jobs':mode==='inventory'?'vehicles':'catalogue';
 const load=useCallback(async(force=false)=>{setLoading(true);try{setRecords(await loadRecords(kind,force));setError('');}catch(e){setError(e instanceof Error?e.message:'Rekod gagal dimuatkan.');}finally{setLoading(false)}},[kind]);useEffect(()=>{void load()},[load]);
 const demo=!loading&&!error&&!records.length;const shown=demo?(mode==='garage'?demoJobs:demoVehicles):records;
 const filtered=shown.filter(r=>{const text='brand'in r?r.brand+' '+r.model+' '+r.plate:r.customer+' '+r.bike+' '+r.plate;return text.toLowerCase().includes(query.toLowerCase())&&(status==='all'||r.status===status)&&(mode==='garage'||brand==='all'||('brand'in r&&r.brand===brand))});
 useEffect(()=>{type MC={registerTool:(t:unknown,o:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:MC}).modelContext;if(!ctx)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'filter_motor_records',description:'Filter visible motorcycle stock or garage job cards.',inputSchema:{type:'object',properties:{query:{type:'string'},status:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const i=input as {query?:string;status?:string};if(!i||typeof i!=='object'||(i.query!==undefined&&typeof i.query!=='string')||(i.status!==undefined&&!(i.status==='all'||Object.keys(mode==='garage'?jobStatuses:bikeStatuses).includes(i.status))))throw new Error('Invalid filter');setQuery(i.query||'');setStatus(i.status||'all');return {query:i.query||'',status:i.status||'all'};}},{signal:controller.signal})).catch(console.error);return()=>controller.abort()},[mode]);
 const bikes=shown as Vehicle[];const jobs=shown as Job[];
 const stats=mode==='garage'?[['Job aktif',jobs.filter(j=>['new','working'].includes(j.status)).length,Wrench],['Siap diambil',jobs.filter(j=>j.status==='ready').length,CircleCheck],['Nilai servis',money(jobs.reduce((s,j)=>s+total(j),0)),Banknote],['Baki bayaran',money(jobs.reduce((s,j)=>s+total(j)-j.paid,0)),Wallet]]:mode==='inventory'?[['Jumlah stok',bikes.length,Package],['Available',bikes.filter(v=>v.status==='available').length,Bike],['Nilai stok aktif',money(bikes.filter(v=>v.status!=='sold').reduce((s,v)=>s+v.price,0)),Banknote],['Reserved',bikes.filter(v=>v.status==='reserved').length,ShieldCheck]]:[];
 const content=<>
  <div className={admin?"page-bar":"page-bar catalogue-bar"}>{admin?<div className="breadcrumb"><SidebarTrigger/><span>Pengurusan</span><ChevronRight size={14}/><b>{mode==='garage'?'Garage':'Inventori'}</b></div>:<Logo/>}<div className="bar-right">{admin?<span className="access"><ShieldCheck size={15}/> Admin</span>:<a className="quiet-link" href="#inventory"><ShieldCheck size={16}/> Akses admin</a>}{admin?<span className="edition">3AM / 02</span>:<span className="catalogue-header-label">KATALOG RASMI</span>}</div></div>
  <main className={'workspace '+(admin?'admin-workspace':'catalogue-workspace')}>
   {mode==='catalogue'?<><section className="catalogue-hero" aria-label="Selamat datang ke 3 Abdul Motor"><div className="hero-copy"><span className="hero-kicker"><span/>3 ABDUL MOTOR</span><h1>Motor pilihan.<br/><em>Perjalanan baharu.</em></h1><p>Selamat datang ke katalog kami. Terokai pilihan motosikal dan semak harga serta status stok dengan mudah.</p><button className="btn primary hero-action" onClick={()=>document.getElementById('catalogue-stock')?.scrollIntoView({behavior:'smooth',block:'start'})}>Terokai stok <ChevronRight size={18}/></button><div className="hero-services"><span><Bike size={17}/>Jual beli motosikal</span><span><Wrench size={17}/>Servis & penyelenggaraan</span></div></div><div className="hero-brand-art"><div className="hero-orbit"/><img src="./logo-transparent-v2.png" alt="3 Abdul Motor"/><span className="hero-brand-caption">JUAL BELI · SERVIS</span></div></section><section className="catalogue-heading" id="catalogue-stock"><div><span className="eyebrow">KATALOG 3 ABDUL MOTOR</span><h1>Stok motosikal<span className="yellow-period">.</span></h1><p>Semak model, harga dan status stok di sini.</p></div><div className="catalogue-summary"><div><span>Available</span><b>{loading?"—":bikes.filter(v=>v.status==='available').length}</b></div><div><span>Reserved</span><b>{loading?"—":bikes.filter(v=>v.status==='reserved').length}</b></div></div></section></>:<section className="title-row"><div><span className="eyebrow">3 ABDUL MOTOR / {mode==='garage'?'SERVIS & PENYELENGGARAAN':'INVENTORI & JUALAN'}</span><h1>{mode==='garage'?'Garage':'Inventori motosikal'}<span className="yellow-period">.</span></h1><p>{mode==='garage'?'Urus kerja servis, alat ganti dan bayaran pelanggan.':'Urus stok jualan, pemeriksaan dan paparan katalog.'}</p></div><button className="btn primary" onClick={()=>{setAdding(true);setSelected(null)}}><Plus size={18}/>{mode==='garage'?'Job baharu':'Tambah motosikal'}</button></section>}
   {demo&&<div className="demo-banner"><Layers size={16}/><span><b>Paparan contoh</b> · {admin?'Tambah rekod pertama untuk mula menggunakan sistem.':'Stok sebenar belum dimasukkan. Harga di bawah ialah contoh.'}</span></div>}
   {error&&<div className="error-banner" role="alert"><span>{error}</span><button className="btn subtle" onClick={()=>void load(true)}><RefreshCw size={16}/>Cuba semula</button></div>}
   {admin&&<div className="stats">{stats.map(([label,value,Icon])=>{const I=Icon as typeof Bike;return <div className="stat" key={String(label)}><div><span>{String(label)}</span><I size={18}/></div><strong>{String(value)}</strong>{demo&&<small>Data contoh</small>}</div>})}</div>}
   <section className="records-section"><div className="section-label"><div><span className="section-number">{mode==='garage'?'02':'01'}</span><h2>{mode==='garage'?'Job board':mode==='inventory'?'Senarai stok':'Senarai motosikal'}</h2><span className="count">{filtered.length}</span></div><button className="btn subtle refresh-records" disabled={loading} onClick={()=>void load(true)} aria-label="Muat semula rekod"><RefreshCw size={16}/><span>Muat semula</span></button></div>
   <div className="filters"><div className="search"><Search size={18}/><input aria-label="Cari rekod" placeholder={mode==='garage'?'Cari pelanggan, motor atau nombor plat…':'Cari jenama, model atau nombor plat…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Kosongkan carian" onClick={()=>setQuery('')}><X size={16}/></button>}</div>{mode!=='garage'&&<Picker value={brand} onChange={setBrand} options={{all:'Semua jenama',...Object.fromEntries([...new Set(bikes.map(v=>v.brand))].map(b=>[b,b]))}}/>}<Picker value={status} onChange={setStatus} options={{all:'Semua status',...(mode==='garage'?jobStatuses:bikeStatuses)}}/></div>
   {loading?<div className="bike-grid">{[1,2,3].map(i=><div key={i} className="loading-card"><Skeleton className="h-44 w-full"/><Skeleton className="mt-4 h-7 w-2/3"/><Skeleton className="mt-4 h-6 w-1/2"/></div>)}</div>:error?null:mode==='garage'?<div className="garage-board">{Object.keys(jobStatuses).filter(s=>status==='all'||status===s).map(s=><section className={'job-column '+s} key={s}><header><h3>{jobStatuses[s]}</h3><span>{filtered.filter(j=>j.status===s).length}</span></header>{filtered.filter(j=>j.status===s).map(r=>{const j=r as Job;return <button className="job-card" key={j.id} onClick={()=>setDetail(j)}><div className="job-top"><span>{jobId(j.id)}</span><Wrench size={16}/></div><h4>{j.bike}</h4><b className="plate">{j.plate}</b><p>{j.complaint}</p><div className="job-customer"><span>{j.customer}</span><span>{j.mechanic||'Belum ditugaskan'}</span></div><div className="job-bottom"><strong>{money(total(j))}</strong><span className={j.paid>=total(j)&&total(j)>0?'paid':'unpaid'}>{j.paid>=total(j)&&total(j)>0?'Dibayar':'Baki '+money(total(j)-j.paid)}</span></div></button>})}{!filtered.some(j=>j.status===s)&&<div className="empty-column">Tiada job</div>}</section>)}</div>:<div className="bike-grid">{filtered.map(r=>{const v=r as Vehicle;return <article className="bike-card" key={v.id}><button className="photo-button" aria-label={'Lihat '+v.brand+' '+v.model} onClick={()=>setDetail(v)}><BikePhoto v={v}/></button><div className="bike-info"><div className="bike-meta"><span>{v.brand}</span><span>{demo?'CONTOH':vehicleId(v.id)}</span></div><h3>{v.model}</h3><div className="bike-specs"><span><CalendarDays size={15}/>{v.year}</span><span><Gauge size={15}/>{v.mileage.toLocaleString()} km</span></div><div className="bike-bottom"><strong>{money(v.price)}</strong><button className="btn subtle" onClick={()=>setDetail(v)}>{admin?'Urus stok':'Lihat butiran'}</button></div>{admin&&<div className="visibility"><Eye size={14}/>{v.published?'Dipaparkan di katalog':'Tersembunyi dari katalog'}</div>}</div></article>})}</div>}
   {!loading&&!error&&filtered.length===0&&<div className="empty-state"><Package size={36}/><h3>Tiada rekod dijumpai</h3><p>Cuba carian atau status lain.</p><button className="btn subtle" onClick={()=>{setQuery('');setStatus('all');setBrand('all')}}>Kosongkan penapis</button></div>}
   </section><footer className="page-footer"><span>© {new Date().getFullYear()} 3 Abdul Motor</span><span>Powered by <b>BinaLab</b></span></footer>
  </main>
  {admin&&<nav className="mobile-navigation" aria-label="Navigasi utama">{nav.map(n=><a key={n.mode} href={n.href} aria-current={mode===n.mode?'page':undefined} className={mode===n.mode?'active':''}><n.icon size={21}/><span>{n.label}</span></a>)}</nav>}
 </>;
 return <><Toaster richColors position="top-center"/>{admin?<SidebarProvider className="motor-shell"><Sidebar className="motor-sidebar"><SidebarHeader><Logo/></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.mode}><SidebarMenuButton asChild isActive={mode===n.mode}><a href={n.href}><n.icon size={19}/><span>{n.label}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><Wrench size={25}/><strong>Satu operasi.<br/>Dua bahagian.</strong><p>Stok jualan dan servis pelanggan dalam satu pengurusan.</p></div></SidebarContent><SidebarFooter><span className="sidebar-company">3AM MANAGEMENT</span><small>Inventory / Garage</small></SidebarFooter></Sidebar><SidebarInset>{content}</SidebarInset></SidebarProvider>:content}
  <Dialog open={!!detail} onOpenChange={o=>{if(!o)setDetail(null)}}><DialogContent className="motor-dialog detail-dialog"><DialogHeader><DialogTitle>{detail&&('brand'in detail?detail.brand+' '+detail.model:jobId(detail.id))}</DialogTitle><DialogDescription>{demo?'Rekod contoh untuk pratonton.':mode==='garage'?'Butiran servis pelanggan.':'Butiran motosikal.'}</DialogDescription></DialogHeader>{detail&&('brand'in detail?<><BikePhoto v={detail}/><div className="detail-stats"><span>Tahun<b>{detail.year}</b></span><span>Jarak<b>{detail.mileage.toLocaleString()} km</b></span><span>Harga<b>{money(detail.price)}</b></span></div><p className="description">{detail.description||'Tiada keterangan tambahan.'}</p>{admin&&<><div className="detail-stats"><span>Kos beli<b>{money(detail.cost)}</b></span><span>Kos persediaan<b>{money(detail.prep)}</b></span><span>Bayaran diterima<b>{money(detail.paid)}</b></span></div><button className="btn primary" disabled={demo} onClick={()=>{setSelected(detail);setDetail(null)}}>Edit motosikal</button></>}</>:<><div className="job-detail-heading"><div><h3>{detail.bike}</h3><span className="plate">{detail.plate}</span></div><Badge status={detail.status} garage/></div><div className="detail-stats"><span>Pelanggan<b>{detail.customer}</b></span><span>Telefon<b>{detail.phone||'—'}</b></span><span>Mekanik<b>{detail.mechanic||'—'}</b></span></div><div className="service-notes"><b>Aduan / permintaan</b><p>{detail.complaint}</p>{detail.notes&&<><b>Nota kerja</b><p>{detail.notes}</p></>}</div><Table><TableHeader><TableRow><TableHead>Butiran</TableHead><TableHead>Kuantiti</TableHead><TableHead className="text-right">Jumlah</TableHead></TableRow></TableHeader><TableBody>{parseLines(detail.items).map((l,i)=><TableRow key={i}><TableCell>{l.name}<small className="block muted">{l.kind==='part'?'Alat ganti':'Upah'}</small></TableCell><TableCell>{l.qty}</TableCell><TableCell className="text-right">{money(l.qty*l.rate)}</TableCell></TableRow>)}</TableBody></Table><div className="invoice-totals"><span>Jumlah<strong>{money(total(detail))}</strong></span><span>Dibayar<strong>{money(detail.paid)}</strong></span><span>Baki<strong>{money(total(detail)-detail.paid)}</strong></span></div><div className="dialog-actions"><button className="btn subtle" onClick={()=>printJob(detail)}><Printer size={16}/>Cetak job card</button><button className="btn primary" disabled={demo} onClick={()=>{setSelected(detail);setDetail(null)}}>Edit job & bayaran</button></div></>)}</DialogContent></Dialog>
  {(adding||selected)&&<RecordEditor mode={mode==='garage'?'garage':'inventory'} initial={selected} open onClose={()=>{setSelected(null);setAdding(false)}} onSaved={()=>{setSelected(null);setAdding(false);void load()}}/>}
 </>;
}
function RecordEditor({mode,initial,open,onClose,onSaved}:{mode:'inventory'|'garage';initial:Vehicle|Job|null;open:boolean;onClose:()=>void;onSaved:()=>void}){
 const [bike,setBike]=useState<Vehicle>(initial&&'brand'in initial?initial:{...blankBike});const [job,setJob]=useState<Job>(initial&&'customer'in initial?initial:{...blankJob});const [lines,setLines]=useState<Line[]>(parseLines(initial&&'items'in initial?initial.items:'[]'));const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [error,setError]=useState('');const [tab,setTab]=useState('main');
 const b=(key:keyof Vehicle,value:unknown)=>setBike(v=>({...v,[key]:value}));const j=(key:keyof Job,value:unknown)=>setJob(v=>({...v,[key]:value}));const checks:boolean[]=JSON.parse(bike.inspection);const amount=lines.reduce((s,l)=>s+l.qty*l.rate,0);
 async function upload(file:File){setUploading(true);setError('');try{b('photo',await uploadPhoto(file));toast.success('Foto dimuat naik');}catch(e){setError(e instanceof Error?e.message:'Muat naik gagal.')}finally{setUploading(false)}}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{const data=mode==='garage'?{...job,items:JSON.stringify(lines)}:bike;await saveRecord(mode==='garage'?'jobs':'vehicles',data,!!initial);toast.success('Rekod disimpan');onSaved();}catch(e){setError(e instanceof Error?e.message:'Tidak dapat menyimpan.')}finally{setSaving(false)}}
 return <Dialog open={open} onOpenChange={o=>{if(!o&&!saving&&!uploading)onClose()}}><DialogContent className="motor-dialog editor-dialog"><DialogHeader><DialogTitle>{initial?'Edit':'Tambah'} {mode==='garage'?'job servis':'motosikal'}</DialogTitle><DialogDescription>{mode==='garage'?'Rekod motosikal pelanggan, kerja servis dan bayaran.':'Maklumat jualan dan pemeriksaan stok.'}</DialogDescription></DialogHeader><form onSubmit={save}>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="editor-tabs"><TabsTrigger value="main">{mode==='garage'?'Pelanggan & kerja':'Maklumat stok'}</TabsTrigger><TabsTrigger value="finance">{mode==='garage'?'Caj & bayaran':'Kos & bayaran'}</TabsTrigger>{mode==='inventory'&&<TabsTrigger value="inspection">Pemeriksaan</TabsTrigger>}</TabsList></Tabs>
 {mode==='inventory'?<>
 <div hidden={tab!=='main'} className="form-panel"><div className="form-grid"><Field label="Jenama *"><input required={tab==='main'} value={bike.brand} onChange={e=>b('brand',e.target.value)} placeholder="Yamaha"/></Field><Field label="Model *"><input required={tab==='main'} value={bike.model} onChange={e=>b('model',e.target.value)} placeholder="Y15ZR"/></Field><NumberField label="Tahun" value={bike.year} onChange={n=>b('year',n)}/><Field label="Nombor plat"><input value={bike.plate} onChange={e=>b('plate',e.target.value.toUpperCase())}/></Field><NumberField label="Jarak (km)" value={bike.mileage} onChange={n=>b('mileage',n)}/><Field label="Status"><Picker value={bike.status} onChange={s=>b('status',s)} options={bikeStatuses}/></Field><NumberField label="Harga jualan (RM)" value={bike.price} cents onChange={n=>b('price',n)}/><div className="switch-field"><span>Paparkan di katalog</span><Switch aria-label="Paparkan di katalog" checked={!!bike.published} onCheckedChange={v=>b('published',v?1:0)}/></div></div><Field label="Keterangan katalog"><textarea rows={3} value={bike.description} onChange={e=>b('description',e.target.value)}/></Field><label className="photo-upload"><ImagePlus size={24}/><span>{uploading?'Memuat naik…':bike.photo?'Tukar foto motosikal':'Muat naik foto motosikal'}<small>JPG / PNG / WebP · maks. 20 MB · Auto kecilkan ≤256 KB</small></span><input type="file" accept="image/jpeg,image/png,image/webp" disabled={uploading} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0])}}/></label>{bike.photo&&<img className="upload-preview" src={bike.photo} alt="Foto stok"/>}</div>
 <div hidden={tab!=='finance'} className="form-panel"><div className="form-grid"><NumberField label="Kos beli (RM)" value={bike.cost} cents onChange={n=>b('cost',n)}/><NumberField label="Kos persediaan (RM)" value={bike.prep} cents onChange={n=>b('prep',n)}/><NumberField label="Bayaran diterima (RM)" value={bike.paid} cents onChange={n=>b('paid',n)}/><Field label="Nama pembeli"><input value={bike.buyer} onChange={e=>b('buyer',e.target.value)}/></Field></div><div className="invoice-totals"><span>Baki bayaran<strong>{money(Math.max(0,bike.price-bike.paid))}</strong></span><span>Anggaran untung kasar<strong>{money(bike.price-bike.cost-bike.prep)}</strong></span></div><p className="form-note">Status Sold memerlukan bayaran penuh. Kos beli, kos persediaan dan maklumat pembeli hanya kelihatan kepada admin.</p></div>
 <div hidden={tab!=='inspection'} className="form-panel"><label className="check-row select-all"><Checkbox checked={inspectionLabels.every((_,i)=>checks[i])} onCheckedChange={v=>b('inspection',JSON.stringify(inspectionLabels.map(()=>!!v)))}/><b>Pilih semua</b></label>{inspectionLabels.map((l,i)=><label className="check-row" key={l}><Checkbox checked={!!checks[i]} onCheckedChange={v=>b('inspection',JSON.stringify(inspectionLabels.map((_,k)=>k===i?!!v:!!checks[k])))}/><span>{l}</span></label>)}</div>
 </>:<>
 <div hidden={tab!=='main'} className="form-panel"><div className="form-grid"><Field label="Nama pelanggan *"><input required={tab==='main'} value={job.customer} onChange={e=>j('customer',e.target.value)}/></Field><Field label="Telefon"><input type="tel" value={job.phone} onChange={e=>j('phone',e.target.value)}/></Field><Field label="Motosikal *"><input required={tab==='main'} value={job.bike} placeholder="Yamaha Y15ZR" onChange={e=>j('bike',e.target.value)}/></Field><Field label="Nombor plat *"><input required={tab==='main'} value={job.plate} onChange={e=>j('plate',e.target.value.toUpperCase())}/></Field><NumberField label="Jarak (km)" value={job.mileage} onChange={n=>j('mileage',n)}/><Field label="Mekanik"><input value={job.mechanic} onChange={e=>j('mechanic',e.target.value)}/></Field><Field label="Status kerja"><Picker value={job.status} onChange={s=>j('status',s)} options={jobStatuses}/></Field></div><Field label="Aduan / permintaan pelanggan *"><textarea required={tab==='main'} rows={3} value={job.complaint} onChange={e=>j('complaint',e.target.value)}/></Field><Field label="Nota kerja"><textarea rows={3} value={job.notes} onChange={e=>j('notes',e.target.value)}/></Field></div>
 <div hidden={tab!=='finance'} className="form-panel"><div className="line-header"><h3>Alat ganti & upah</h3><button type="button" className="btn subtle" onClick={()=>setLines(v=>[...v,{name:'',kind:'part',qty:1,rate:0}])}><Plus size={16}/>Tambah item</button></div>{!lines.length&&<p className="form-note">Tambah alat ganti atau upah untuk mengira jumlah servis.</p>}{lines.map((l,i)=><div className="service-line" key={i}><Field label="Butiran"><input required={tab==='finance'} value={l.name} onChange={e=>setLines(v=>v.map((a,k)=>k===i?{...a,name:e.target.value}:a))}/></Field><Field label="Jenis"><Picker value={l.kind} onChange={s=>setLines(v=>v.map((a,k)=>k===i?{...a,kind:s}:a))} options={{part:'Alat ganti',labour:'Upah'}}/></Field><NumberField label="Kuantiti" value={l.qty} onChange={n=>setLines(v=>v.map((a,k)=>k===i?{...a,qty:n}:a))}/><NumberField label="Harga (RM)" value={l.rate} cents onChange={n=>setLines(v=>v.map((a,k)=>k===i?{...a,rate:n}:a))}/><button type="button" className="icon-button" aria-label="Buang item" onClick={()=>setLines(v=>v.filter((_,k)=>k!==i))}><X size={18}/></button></div>)}<NumberField label="Bayaran diterima (RM)" value={job.paid} cents onChange={n=>j('paid',n)}/><div className="invoice-totals"><span>Jumlah servis<strong>{money(amount)}</strong></span><span>Baki<strong>{money(amount-job.paid)}</strong></span></div></div>
 </>}
 {error&&<p className="form-error" role="alert">{error}</p>}<div className="dialog-actions"><button type="button" className="btn subtle" disabled={saving||uploading} onClick={onClose}>Batal</button><button type="submit" className="btn primary" disabled={saving||uploading}>{saving?'Menyimpan…':'Simpan rekod'}</button></div></form></DialogContent></Dialog>
}
function printJob(job:Job){const w=window.open('','_blank');if(!w){toast.error('Benarkan pop-up untuk mencetak job card.');return}const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));w.document.write('<!doctype html><html><head><title>'+jobId(job.id)+'</title><style>body{font-family:Arial;padding:32px;color:#111}h1{border-bottom:5px solid #ffd21c;padding-bottom:20px}table{border-collapse:collapse;width:100%;margin-top:25px}td,th{padding:12px;border-bottom:1px solid #ddd;text-align:left}small{color:#555}.totals{text-align:right;margin-top:30px}</style></head><body><h1>3 ABDUL MOTOR</h1><h2>Job card · '+jobId(job.id)+'</h2><p>'+esc(job.customer)+' · '+esc(job.phone)+'</p><p><b>'+esc(job.bike)+' / '+esc(job.plate)+'</b></p><p>Status: '+jobStatuses[job.status]+' · Mekanik: '+esc(job.mechanic||'—')+'</p><p>'+esc(job.complaint)+'</p><p>'+esc(job.notes)+'</p><table><tr><th>Butiran</th><th>Kuantiti</th><th>Harga</th><th>Jumlah</th></tr>'+parseLines(job.items).map(l=>'<tr><td>'+esc(l.name)+'</td><td>'+l.qty+'</td><td>'+money(l.rate)+'</td><td>'+money(l.qty*l.rate)+'</td></tr>').join('')+'</table><div class="totals"><p>Jumlah: <b>'+money(total(job))+'</b></p><p>Dibayar: '+money(job.paid)+'</p><p>Baki: <b>'+money(total(job)-job.paid)+'</b></p></div></body></html>');w.document.close();w.focus();w.print();}
