'use client';
import {useState,useEffect,useCallback} from 'react';
import {loadRecords,getRecord,loadSettings,photoPaths,signPhotos} from '@/lib/records';
import {VisitorCounter} from './visitor-counter';
import {MotorFooter} from './motor-footer';
import {can} from '@/lib/staff';
import type {StaffProfile} from '@/lib/staff';
import {getStaff} from '@/lib/supabase';
import {RecordEditor} from './record-editor';
import {PaymentPanel,InventoryTools,OwnerPanel,ServiceHistory,ShareButton} from './operations-ui';
import {whatsappLink} from '@/lib/business';
import type {BusinessSettings} from '@/lib/business';
import {Bike, Wrench, Package, Search, Plus, ShieldCheck, Gauge, CalendarDays, CircleCheck, Wallet, X, RefreshCw, Eye, Banknote, Layers, ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {SidebarProvider,Sidebar,SidebarHeader,SidebarContent,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarInset,SidebarTrigger} from '@/components/ui/sidebar';
import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell} from '@/components/ui/table';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {Vehicle,Job,demoVehicles,demoJobs,money,total,parseLines,vehicleId,jobId,paymentStatus,bikeStatuses,jobStatuses} from '@/lib/motor';

type Mode='catalogue'|'inventory'|'garage';
function Picker({value,onChange,options}:{value:string;onChange:(s:string)=>void;options:Record<string,string>}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="picker"><SelectValue/></SelectTrigger><SelectContent>{Object.entries(options).map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Badge({status,garage=false}:{status:string;garage?:boolean}){return <span className={'status '+status}>{(garage?jobStatuses:bikeStatuses)[status]}</span>}
function Logo(){return <a className="brand" href="#catalogue" aria-label="3 Abdul Motor — katalog"><img src="./logo-transparent-v2.png" alt="3 Abdul Motor"/><span className="brand-caption">Jual beli · Servis</span></a>}
function BikePhoto({v}:{v:Vehicle}){return <div className={'bike-photo '+(!v.photo?'no-photo':'')}>{v.photo?<img src={v.photo} alt={v.brand+' '+v.model} loading="lazy" decoding="async"/>:<><Bike size={76} strokeWidth={1.1}/><span>Foto belum dimuat naik</span></>}<Badge status={v.status}/></div>}
const nav=[{mode:'catalogue',href:'#catalogue',label:'Katalog',icon:Bike},{mode:'inventory',href:'#inventory',label:'Inventori',icon:Package},{mode:'garage',href:'#garage',label:'Garage',icon:Wrench}];
export default function MotorApp({mode}:{mode:Mode}){
 const admin=mode!=='catalogue';const [records,setRecords]=useState<(Vehicle|Job)[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');const [status,setStatus]=useState('all');const [brand,setBrand]=useState('all');const [selected,setSelected]=useState<Vehicle|Job|null>(null);const [adding,setAdding]=useState(false);const [detail,setDetail]=useState<Vehicle|Job|null>(null);
 const [demo,setDemo]=useState(false);const [owner,setOwner]=useState(false);const [staff,setStaff]=useState<StaffProfile|null>(null);const [settings,setSettings]=useState<BusinessSettings|null>(null);
 useEffect(()=>{if(admin)void getStaff().then(s=>{setStaff(s);setOwner(s?.role==='owner')}).catch(()=>setOwner(false));void loadSettings().then(setSettings).catch(()=>{});},[admin]);
 const navigation=owner?[...nav,{mode:'staff',href:'#staff',label:'Akses staf',icon:ShieldCheck}]:nav;const editable=can(staff,mode==='garage'?'garage_edit':'inventory_edit');
 const kind=mode==='garage'?'jobs':mode==='inventory'?'vehicles':'catalogue';
 const load=useCallback(async(force=false)=>{setLoading(true);try{setRecords(await loadRecords(kind,force));setError('');}catch(e){setError(e instanceof Error?e.message:'Rekod gagal dimuatkan.');}finally{setLoading(false)}},[kind]);useEffect(()=>{void load()},[load]);
 const shown=demo?(mode==='garage'?demoJobs:demoVehicles):records;
 const filtered=shown.filter(r=>{const text='brand'in r?r.brand+' '+r.model+' '+(r.plate||''):r.customer+' '+r.bike+' '+r.plate;return text.toLowerCase().includes(query.toLowerCase())&&(status==='all'||r.status===status)&&(mode==='garage'||brand==='all'||('brand'in r&&r.brand===brand))});
 useEffect(()=>{type MC={registerTool:(t:unknown,o:{signal:AbortSignal})=>void|Promise<void>};const ctx=(document as Document&{modelContext?:MC}).modelContext;if(!ctx)return;const controller=new AbortController();Promise.resolve(ctx.registerTool({name:'filter_motor_records',description:'Filter visible motorcycle stock or garage job cards.',inputSchema:{type:'object',properties:{query:{type:'string'},status:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true},execute:async(input:unknown)=>{const i=input as {query?:string;status?:string};if(!i||typeof i!=='object'||(i.query!==undefined&&typeof i.query!=='string')||(i.status!==undefined&&!(i.status==='all'||Object.keys(mode==='garage'?jobStatuses:bikeStatuses).includes(i.status))))throw new Error('Invalid filter');setQuery(i.query||'');setStatus(i.status||'all');return {query:i.query||'',status:i.status||'all'};}},{signal:controller.signal})).catch(console.error);return()=>controller.abort()},[mode]);
 const bikes=shown as Vehicle[];const jobs=shown as Job[];
 const stats=mode==='garage'?[['Job aktif',jobs.filter(j=>['new','working'].includes(j.status)).length,Wrench],['Siap diambil',jobs.filter(j=>j.status==='ready').length,CircleCheck],['Nilai servis',money(jobs.reduce((s,j)=>s+total(j),0)),Banknote],['Baki bayaran',money(jobs.reduce((s,j)=>s+total(j)-j.paid,0)),Wallet]]:mode==='inventory'?[['Jumlah stok',bikes.length,Package],['Available',bikes.filter(v=>v.status==='available').length,Bike],['Nilai stok aktif',money(bikes.filter(v=>v.status!=='sold').reduce((s,v)=>s+v.price,0)),Banknote],['Reserved',bikes.filter(v=>v.status==='reserved').length,ShieldCheck]]:[];
 async function openFresh(r:Vehicle|Job){try{setDetail(await getRecord(kind,r.id))}catch(e){toast.error((e as Error).message)}}
 async function editFresh(r:Vehicle|Job){try{const fresh=await getRecord(mode==='garage'?'jobs':'vehicles',r.id);setSelected(fresh);setDetail(null)}catch(e){toast.error((e as Error).message)}}
 async function refreshDetail(){if(!detail)return;setDetail(await getRecord(mode==='garage'?'jobs':'vehicles',detail.id));await load(true)}
 useEffect(()=>{if(mode!=='catalogue')return;const openLink=()=>{const id=Number(new URLSearchParams(location.hash.split('?')[1]||'').get('motor'));if(Number.isInteger(id)&&id>0)void getRecord('catalogue',id).then(setDetail).catch(()=>toast.error('Motosikal ini tidak lagi dipaparkan.'))};openLink();window.addEventListener('hashchange',openLink);return()=>window.removeEventListener('hashchange',openLink)},[mode]);
 const content=<>
  <div className={admin?"page-bar":"page-bar catalogue-bar"}>{admin?<div className="breadcrumb"><SidebarTrigger/><span>Pengurusan</span><ChevronRight size={14}/><b>{mode==='garage'?'Garage':'Inventori'}</b></div>:<Logo/>}<div className="bar-right">{admin?<span className="access"><ShieldCheck size={15}/> Admin</span>:<a className="quiet-link" href="#inventory"><ShieldCheck size={16}/> Akses admin</a>}{admin?<span className="edition">3AM / 02</span>:<span className="catalogue-header-label">KATALOG RASMI</span>}</div></div>
  <main className={'workspace '+(admin?'admin-workspace':'catalogue-workspace')}>
   {mode==='catalogue'?<><section className="catalogue-hero" aria-label="Selamat datang ke 3 Abdul Motor"><div className="hero-copy"><span className="hero-kicker"><span/>3 ABDUL MOTOR</span><h1>Motor pilihan.<br/><em>Perjalanan baharu.</em></h1><p>Selamat datang ke katalog kami. Terokai pilihan motosikal dan semak harga serta status stok dengan mudah.</p><button className="btn primary hero-action" onClick={()=>document.getElementById('catalogue-stock')?.scrollIntoView({behavior:'smooth',block:'start'})}>Terokai stok <ChevronRight size={18}/></button><div className="hero-services"><span><Bike size={17}/>Jual beli motosikal</span><span><Wrench size={17}/>Servis & penyelenggaraan</span></div></div><div className="hero-brand-art"><div className="hero-orbit"/><img src="./logo-transparent-v2.png" alt="3 Abdul Motor"/><span className="hero-brand-caption">JUAL BELI · SERVIS</span></div></section><section className="catalogue-heading" id="catalogue-stock"><div><span className="eyebrow">KATALOG 3 ABDUL MOTOR</span><h1>Stok motosikal<span className="yellow-period">.</span></h1><p>Semak model, harga dan status stok di sini.</p></div><div className="catalogue-summary"><div><span>Available</span><b>{loading?"—":bikes.filter(v=>v.status==='available').length}</b></div><div><span>Reserved</span><b>{loading?"—":bikes.filter(v=>v.status==='reserved').length}</b></div></div></section></>:<section className="title-row"><div><span className="eyebrow">3 ABDUL MOTOR / {mode==='garage'?'SERVIS & PENYELENGGARAAN':'INVENTORI & JUALAN'}</span><h1>{mode==='garage'?'Garage':'Inventori motosikal'}<span className="yellow-period">.</span></h1><p>{mode==='garage'?'Urus kerja servis, alat ganti dan bayaran pelanggan.':'Urus stok jualan, pemeriksaan dan paparan katalog.'}</p></div><button className="btn primary" disabled={!editable} onClick={()=>{setDemo(false);setAdding(true);setSelected(null)}}><Plus size={18}/>{mode==='garage'?'Job baharu':'Tambah motosikal'}</button></section>}
   {admin&&<div className="action-row"><button className="btn subtle" onClick={()=>{setDemo(!demo);setDetail(null)}}>{demo?'Kembali ke rekod sebenar':'Lihat demo'}</button>{mode==='inventory'?<InventoryTools owner={owner} staff={staff} onSettingsChanged={setSettings}/>:owner&&<OwnerPanel/>}</div>}
   {demo&&<div className="demo-banner"><Layers size={16}/><span><b>Paparan contoh</b> · {'Mod demo dipilih. Rekod contoh tidak boleh disimpan atau menerima bayaran.'}</span></div>}
   {admin&&!editable&&staff&&<p className="form-note access-note">Akses baca sahaja untuk {mode==='garage'?'job garaj':'stok inventori'}. Had bayaran dan tindakan lain ditetapkan oleh owner.</p>}
   {error&&<div className="error-banner" role="alert"><span>{error}</span><button className="btn subtle" onClick={()=>void load(true)}><RefreshCw size={16}/>Cuba semula</button></div>}
   {admin&&<div className="stats">{stats.map(([label,value,Icon])=>{const I=Icon as typeof Bike;return <div className="stat" key={String(label)}><div><span>{String(label)}</span><I size={18}/></div><strong>{String(value)}</strong>{demo&&<small>Data contoh</small>}</div>})}</div>}
   <section className="records-section"><div className="section-label"><div><span className="section-number">{mode==='garage'?'02':'01'}</span><h2>{mode==='garage'?'Job board':mode==='inventory'?'Senarai stok':'Senarai motosikal'}</h2><span className="count">{filtered.length}</span></div><button className="btn subtle refresh-records" disabled={loading} onClick={()=>void load(true)} aria-label="Muat semula rekod"><RefreshCw size={16}/><span>Muat semula</span></button></div>
   <div className="filters"><div className="search"><Search size={18}/><input aria-label="Cari rekod" placeholder={mode==='garage'?'Cari pelanggan, motor atau nombor plat…':mode==='catalogue'?'Cari jenama atau model…':'Cari jenama, model atau nombor plat…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Kosongkan carian" onClick={()=>setQuery('')}><X size={16}/></button>}</div>{mode!=='garage'&&<Picker value={brand} onChange={setBrand} options={{all:'Semua jenama',...Object.fromEntries([...new Set(bikes.map(v=>v.brand))].map(b=>[b,b]))}}/>}<Picker value={status} onChange={setStatus} options={{all:'Semua status',...(mode==='garage'?Object.fromEntries(Object.entries(jobStatuses).filter(([s])=>s!=='collected')):bikeStatuses)}}/></div>
   {loading?<div className="bike-grid">{[1,2,3].map(i=><div key={i} className="loading-card"><Skeleton className="h-44 w-full"/><Skeleton className="mt-4 h-7 w-2/3"/><Skeleton className="mt-4 h-6 w-1/2"/></div>)}</div>:error?null:mode==='garage'?<div className="garage-board">{Object.keys(jobStatuses).filter(s=>s!=='collected'&&(status==='all'||status===s)).map(s=><section className={'job-column '+s} key={s}><header><h3>{jobStatuses[s]}</h3><span>{filtered.filter(j=>j.status===s).length}</span></header>{filtered.filter(j=>j.status===s).map(r=>{const j=r as Job;return <button className="job-card" key={j.id} onClick={()=>demo?setDetail(j):void openFresh(j)}><div className="job-top"><span>{jobId(j.id)}</span><Wrench size={16}/></div><h4>{j.bike}</h4><b className="plate">{j.plate}</b><p>{j.complaint}</p><div className="job-customer"><span>{j.customer}</span><span>{j.mechanic||'Belum ditugaskan'}</span></div><div className="job-bottom"><strong>{money(total(j))}</strong><span className={j.paid>=total(j)&&total(j)>0?'paid':'unpaid'}>{total(j)===0?(j.status==='new'?'Caj belum ditetapkan':'Percuma'):j.paid>=total(j)?'Dibayar penuh':'Baki '+money(total(j)-j.paid)}</span></div></button>})}{!filtered.some(j=>j.status===s)&&<div className="empty-column">Tiada job</div>}</section>)}</div>:<div className="bike-grid">{filtered.map(r=>{const v=r as Vehicle;return <article className="bike-card" key={v.id}><button className="photo-button" aria-label={'Lihat '+v.brand+' '+v.model} onClick={()=>admin&&!demo?void openFresh(v):setDetail(v)}><BikePhoto v={v}/></button><div className="bike-info"><div className="bike-meta"><span>{v.brand}</span><span>{demo?'CONTOH':vehicleId(v.id)}</span></div><h3>{v.model}</h3><div className="bike-specs"><span><CalendarDays size={15}/>{v.year}</span><span><Gauge size={15}/>{v.mileage.toLocaleString()} km</span></div><div className="bike-bottom"><strong>{money(v.price)}</strong><button className="btn subtle" onClick={()=>admin&&!demo?void openFresh(v):setDetail(v)}>{admin?'Urus stok':'Lihat butiran'}</button></div>{admin&&<div className="visibility"><Eye size={14}/>{v.published?'Dipaparkan di katalog':'Tersembunyi dari katalog'}</div>}</div></article>})}</div>}
   {!loading&&!error&&filtered.length===0&&<div className="empty-state"><Package size={36}/><h3>Tiada rekod dijumpai</h3><p>{records.length?'Cuba carian atau status lain.':admin?'Belum ada rekod. Tambah rekod pertama untuk mula.':'Stok belum tersedia. Sila semak semula kemudian.'}</p><button className="btn subtle" onClick={()=>{setQuery('');setStatus('all');setBrand('all')}}>Kosongkan penapis</button></div>}
   </section>{mode==='garage'&&!demo&&<ServiceHistory onSelect={j=>void openFresh(j)}/>}{mode==='catalogue'&&<VisitorCounter/>}<MotorFooter/>
  </main>
  {admin&&<nav className="mobile-navigation" aria-label="Navigasi utama">{navigation.map(n=><a key={n.mode} href={n.href} aria-current={mode===n.mode?'page':undefined} className={mode===n.mode?'active':''}><n.icon size={21}/><span>{n.label}</span></a>)}</nav>}
 </>;
 return <><Toaster richColors position="top-center"/>{admin?<SidebarProvider className="motor-shell"><Sidebar className="motor-sidebar"><SidebarHeader><Logo/></SidebarHeader><SidebarContent><p className="nav-label">WORKSPACE</p><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.mode}><SidebarMenuButton asChild isActive={mode===n.mode}><a href={n.href}><n.icon size={19}/><span>{n.label}</span></a></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="sidebar-note"><Wrench size={25}/><strong>Satu operasi.<br/>Dua bahagian.</strong><p>Stok jualan dan servis pelanggan dalam satu pengurusan.</p></div></SidebarContent><SidebarFooter><span className="sidebar-company">3AM MANAGEMENT</span><small>Inventory / Garage</small></SidebarFooter></Sidebar><SidebarInset>{content}</SidebarInset></SidebarProvider>:content}
  <Dialog open={!!detail} onOpenChange={o=>{if(!o){setDetail(null);if(mode==='catalogue')history.replaceState(null,'','#catalogue')}}}><DialogContent className="motor-dialog detail-dialog"><DialogHeader><DialogTitle>{detail&&('brand'in detail?detail.brand+' '+detail.model:jobId(detail.id))}</DialogTitle><DialogDescription>{demo?'Rekod demo sahaja.':mode==='garage'?'Butiran servis pelanggan.':'Butiran motosikal.'}</DialogDescription></DialogHeader>{detail&&<>
  {'brand'in detail?<><VehicleGallery vehicle={detail}/><div className="detail-stats"><span>Tahun<b>{detail.year}</b></span><span>Jarak<b>{detail.mileage.toLocaleString()} km</b></span><span>Harga<b>{money(detail.price)}</b></span></div><p className="description">{detail.description||'Tiada keterangan tambahan.'}</p>{!demo&&(mode==='catalogue'||!!detail.published)&&<div className="action-row"><ShareButton id={detail.id}/>{settings&&whatsappLink(settings,detail)&&<a className="btn primary" target="_blank" rel="noopener noreferrer" href={whatsappLink(settings,detail)}>Tanya melalui WhatsApp</a>}</div>}{admin&&<><div className="detail-stats"><span>Kos beli<b>{money(detail.cost)}</b></span><span>Persediaan<b>{money(detail.prep)}</b></span><span>Nombor casis<b>{detail.chassis||'—'}</b></span><span>Pembekal<b>{detail.supplier||'—'}</b></span><span>Telefon pembekal<b>{detail.supplierPhone||'—'}</b></span><span>Pembeli<b>{detail.buyer||'—'}</b></span><span>Telefon pembeli<b>{detail.buyerPhone||'—'}</b></span></div>{parseLines(detail.prepItems||'[]').map((l,i)=><p key={i} className="muted">{l.name} × {l.qty} · {money(l.qty*l.rate)}</p>)}</>}</>:<><div className="job-detail-heading"><div><h3>{detail.bike}</h3><span className="plate">{detail.plate}</span></div><Badge status={detail.status} garage/></div><div className="detail-stats"><span>Pelanggan<b>{detail.customer}</b></span><span>Telefon<b>{detail.phone||'—'}</b></span><span>Mekanik<b>{detail.mechanic||'—'}</b></span></div><div className="service-notes"><b>Aduan / permintaan</b><p>{detail.complaint}</p>{detail.notes&&<><b>Nota kerja</b><p>{detail.notes}</p></>}<b>Persetujuan anggaran</b><p>{detail.estimateStatus==='approved'?'Diluluskan · '+money(detail.approvedTotal||0):detail.estimateStatus==='sent'?'Anggaran telah diberi':'Draf'}</p>{detail.approvalNote&&<p>{detail.approvalNote}</p>}{detail.creditApprovedAt&&<p>Penyerahan dengan baki diluluskan owner: {detail.creditReason}</p>}</div><Table><TableHeader><TableRow><TableHead>Butiran</TableHead><TableHead>Kuantiti</TableHead><TableHead className="text-right">Jumlah</TableHead></TableRow></TableHeader><TableBody>{parseLines(detail.items).map((l,i)=><TableRow key={i}><TableCell>{l.name}</TableCell><TableCell>{l.qty}</TableCell><TableCell className="text-right">{money(l.qty*l.rate)}</TableCell></TableRow>)}</TableBody></Table></>}
  {admin&&<><button className="btn primary" disabled={demo||!editable} onClick={()=>void editFresh(detail)}>Edit {mode==='garage'?'job':'motosikal'}</button>{!demo&&<PaymentPanel record={detail} owner={owner} staff={staff} onChanged={refreshDetail}/>}</>}
  </>}</DialogContent></Dialog>
  {(adding||selected)&&<RecordEditor mode={mode==='garage'?'garage':'inventory'} initial={selected} owner={owner} staff={staff} inventory={mode==='inventory'?records as Vehicle[]:[]} onClose={()=>{setSelected(null);setAdding(false)}} onSaved={r=>{setSelected(null);setAdding(false);void load(true);void openFresh(r)}}/>}
 </>;
}
function VehicleGallery({vehicle}:{vehicle:Vehicle}){const [urls,setUrls]=useState<Record<string,string>>({});const [active,setActive]=useState(0);const keys=photoPaths(vehicle);const signature=JSON.stringify(keys);useEffect(()=>{let live=true;setActive(0);void signPhotos(JSON.parse(signature)).then(v=>{if(live)setUrls(v)}).catch(()=>{});return()=>{live=false}},[signature]);return <><BikePhoto v={{...vehicle,photo:urls[keys[active]]||vehicle.photo}}/>{keys.length>1&&<div className="gallery-thumbnails">{keys.map((k,i)=><button key={k} aria-label={'Lihat foto '+(i+1)} aria-pressed={active===i} onClick={()=>setActive(i)}><img src={urls[k]} alt={'Foto '+(i+1)}/></button>)}</div>}</>}
