import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {StaffAccess,ChangeStaffPassword} from './components/staff-access';
import {canAccess} from './lib/staff';
import type {StaffProfile} from './lib/staff';
import MotorApp from './components/motor-app';
import {supabase,getStaff} from './lib/supabase';
import {Toaster,toast} from 'sonner';
import './styles.css';
function App(){const [route,setRoute]=useState(location.hash.slice(1).split('?')[0]||'catalogue');const [ready,setReady]=useState(false);const [profile,setProfile]=useState<StaffProfile|null>(null);const [recovery,setRecovery]=useState(false);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
useEffect(()=>{const nav=()=>setRoute(location.hash.slice(1).split('?')[0]||'catalogue');window.addEventListener('hashchange',nav);return()=>window.removeEventListener('hashchange',nav)},[]);
useEffect(()=>{setReady(false);setProfile(null);let live=true;async function check(force=false){if(route==='catalogue'&&!recovery){if(live)setReady(true);return;}try{const p=await getStaff(force);if(live){setProfile(p);setError(p&&!p.must_change_password&&!canAccess(p,route)?'Akaun ini tidak mempunyai akses ke bahagian ini.':'')}}catch(e){if(live)setError((e as Error).message)}finally{if(live)setReady(true)}}void check();const focus=()=>void check(true);window.addEventListener('focus',focus);const sub=supabase?.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')setRecovery(true);setTimeout(()=>void check(true),0)});return()=>{live=false;window.removeEventListener('focus',focus);sub?.data.subscription.unsubscribe()}},[route,recovery]);
async function login(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');try{if(recovery){const {error}=await supabase.auth.updateUser({password});if(error)throw error;setRecovery(false);toast.success('Kata laluan dikemas kini.');}else{const {error}=await supabase.auth.signInWithPassword({email:email.trim(),password});if(error)throw error;const p=await getStaff(true);if(!p){await supabase.auth.signOut();throw Error('Akaun ini belum diberikan akses staf.');}setProfile(p);setReady(true);if(!p.must_change_password&&!canAccess(p,route))setError('Akaun ini tidak mempunyai akses ke bahagian ini.');}}catch(e){setError(e instanceof Error?e.message:'Log masuk gagal.')}finally{setBusy(false)}}
async function forgot(){if(!supabase||!email.trim()){setError('Masukkan e-mel terlebih dahulu.');return}setBusy(true);const {error}=await supabase.auth.resetPasswordForEmail(email.trim(),{redirectTo:location.origin+location.pathname});setBusy(false);if(error)setError('E-mel pemulihan belum dapat dihantar. Hubungi pentadbir.');else toast.success('Jika akaun wujud, pautan pemulihan akan dihantar.');}
const mode=route==='inventory'?'inventory':route==='garage'?'garage':'catalogue';
if(route!=='staff'&&mode==='catalogue'&&!recovery)return <MotorApp mode="catalogue"/>;
if(ready&&profile?.must_change_password&&!recovery)return <ChangeStaffPassword onChanged={()=>{void getStaff(true).then(setProfile).catch(e=>setError((e as Error).message))}}/>;
if(ready&&canAccess(profile,route)&&!recovery)return <><div className="session-strip"><span>3 Abdul Motor · Admin</span><button onClick={async()=>{await supabase?.auth.signOut();setProfile(null);setPassword('')}}>Log keluar</button></div>{route==='staff'?<StaffAccess/>:<MotorApp key={mode} mode={mode}/>}</>;
return <main className="login-page"><Toaster richColors/><a href="#catalogue"><img src="./logo-transparent-v2.png" alt="3 Abdul Motor"/></a><section className="login-card"><span className="eyebrow">AKSES ADMIN</span><h1>{recovery?'Kata laluan baharu':'Selamat datang'}</h1><p>{route==='staff'?'Pengurusan Akses Staf · Owner':mode==='garage'?'Pengurusan Garage':'Pengurusan Inventori & Jual Beli'}</p>{!ready?<p>Mengesahkan sesi…</p>:<form onSubmit={login}>{!recovery&&<label className="field"><span>E-mel</span><input type="email" required autoComplete="username" value={email} onChange={e=>setEmail(e.target.value)}/></label>}<label className="field"><span>Kata laluan</span><input type="password" required minLength={recovery?12:1} autoComplete={recovery?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="form-error" role="alert">{error}</p>}{!supabase&&<p className="form-note">Sistem sedang disediakan. Sila hubungi pentadbir.</p>}<button className="btn primary" disabled={busy||!supabase} type="submit">{busy?'Sila tunggu…':recovery?'Simpan kata laluan':'Log masuk'}</button>{!recovery&&<button type="button" className="forgot-password" onClick={forgot} disabled={busy||!supabase}>Terlupa kata laluan?</button>}</form>}<a className="quiet-link" href="#catalogue">Kembali ke katalog</a></section></main>;
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
